import path from "node:path";
import { access, mkdir, readdir, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { ClawChefError } from "./errors.js";

export interface ScaffoldOptions {
  projectName?: string;
}

export interface ScaffoldResult {
  targetDir: string;
  projectName: string;
}

function normalizeProjectName(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  if (!normalized) {
    throw new ClawChefError("Project name is empty after normalization. Use letters, numbers, spaces, underscore, or dash.");
  }
  return normalized;
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function ensureDirectoryEmpty(targetDir: string): Promise<void> {
  const exists = await pathExists(targetDir);
  if (!exists) {
    await mkdir(targetDir, { recursive: true });
    return;
  }
  const entries = await readdir(targetDir);
  if (entries.length > 0) {
    throw new ClawChefError(`Target directory is not empty: ${targetDir}`);
  }
}

function makePackageJson(projectName: string): string {
  const content = {
    name: `${projectName}-recipe`,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      "test:recipe": "node --test test/recipe-smoke.test.mjs",
      test: "node --test \"test/**/*.test.mjs\"",
    },
    devDependencies: {
      "telegram-api-mock-server": "^0.1.5",
    },
  };
  return `${JSON.stringify(content, null, 2)}\n`;
}

function makeRecipeYaml(projectName: string): string {
  return `version: "1"
name: "${projectName}"

params:
  openclaw_version:
    default: "2026.2.9"
  workspace_name:
    default: "${projectName}"
  agent_name:
    default: "${projectName}"
  agent_model:
    default: "openai/gpt-4.1"
  telegram_mock_api_key:
    required: true

openclaw:
  bin: "openclaw"
  version: "\${openclaw_version}"
  install: "never"
  plugins:
    - "openclaw-telegram-mock-channel"

workspaces:
  - name: "\${workspace_name}"

agents:
  - workspace: "\${workspace_name}"
    name: "\${agent_name}"
    model: "\${agent_model}"

files:
  - workspace: "\${workspace_name}"
    path: "AGENTS.md"
    overwrite: true
    content_from: "./${projectName}-assets/AGENTS.md"

  - workspace: "\${workspace_name}"
    path: "IDENTITY.md"
    overwrite: true
    content_from: "./${projectName}-assets/IDENTITY.md"

  - workspace: "\${workspace_name}"
    path: "SOUL.md"
    overwrite: true
    content_from: "./${projectName}-assets/SOUL.md"

  - workspace: "\${workspace_name}"
    path: "TOOLS.md"
    overwrite: true
    content_from: "./${projectName}-assets/TOOLS.md"

  - workspace: "\${workspace_name}"
    path: "scripts/scheduling.mjs"
    overwrite: true
    content_from: "./${projectName}-assets/scripts/scheduling.mjs"

channels:
  - channel: "telegram-mock"
    account: "default"
    token: "\${telegram_mock_api_key}"
    extra_flags:
      mock_bind: "127.0.0.1:18790"
      mock_api_key: "\${telegram_mock_api_key}"
      mode: "webhook"
`;
}

function makeAgentsDoc(projectName: string): string {
  return `# ${projectName}

Project scaffold generated by clawchef.
`;
}

function makeIdentityDoc(projectName: string): string {
  return `# Identity

You are the ${projectName} assistant.
`;
}

function makeSoulDoc(): string {
  return `# Soul

Keep responses practical, concise, and action-oriented.
`;
}

function makeToolsDoc(): string {
  return `# Tools

- Use available workspace files first.
- Ask for missing secrets explicitly.
`;
}

function makeSchedulingScript(): string {
  return `#!/usr/bin/env node
import process from "node:process";

const message = process.argv.slice(2).join(" ").trim();
if (!message) {
  console.error("Usage: node scripts/scheduling.mjs <message>");
  process.exit(1);
}

console.log("[scheduling] " + message);
`;
}

function makeRecipeSmokeTest(): string {
  return `import test from "node:test";
import assert from "node:assert/strict";
import { access } from "node:fs/promises";

test("recipe scaffold files exist", async () => {
  await access("src/recipe.yaml");
  await access("package.json");
  assert.ok(true);
});
`;
}

export async function scaffoldProject(targetDirArg?: string, options: ScaffoldOptions = {}): Promise<ScaffoldResult> {
  const targetDir = path.resolve(targetDirArg?.trim() ? targetDirArg : process.cwd());
  await ensureDirectoryEmpty(targetDir);

  const defaultName = path.basename(targetDir);
  const rawProjectName = options.projectName?.trim() || defaultName;
  const projectName = normalizeProjectName(rawProjectName);

  const srcDir = path.join(targetDir, "src");
  const assetsDir = path.join(srcDir, `${projectName}-assets`);
  const assetsScriptsDir = path.join(assetsDir, "scripts");
  const testDir = path.join(targetDir, "test");

  await mkdir(srcDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });
  await mkdir(assetsScriptsDir, { recursive: true });
  await mkdir(testDir, { recursive: true });

  await writeFile(path.join(targetDir, "package.json"), makePackageJson(projectName), "utf8");
  await writeFile(path.join(srcDir, "recipe.yaml"), makeRecipeYaml(projectName), "utf8");
  await writeFile(path.join(assetsDir, "AGENTS.md"), makeAgentsDoc(projectName), "utf8");
  await writeFile(path.join(assetsDir, "IDENTITY.md"), makeIdentityDoc(projectName), "utf8");
  await writeFile(path.join(assetsDir, "SOUL.md"), makeSoulDoc(), "utf8");
  await writeFile(path.join(assetsDir, "TOOLS.md"), makeToolsDoc(), "utf8");
  await writeFile(path.join(assetsScriptsDir, "scheduling.mjs"), makeSchedulingScript(), "utf8");
  await writeFile(path.join(testDir, "recipe-smoke.test.mjs"), makeRecipeSmokeTest(), "utf8");

  return {
    targetDir,
    projectName,
  };
}
